apiVersion: v1
kind: Pod
metadata:
  name: backend-tester-pod
  labels:
    name: backend-tester-pod
    app: users-manager-app
spec:
  containers:
    - name: backend-tester
      image: 2205experts/backend_tester_image:latest
  restartPolicy: OnFailure
