apiVersion: v1
kind: Pod
metadata:
  name: restapi-app-pod
  labels:
    name: restapi-app-pod
    app: users-manager-app
spec:
  containers:
    - name: restapi-app
      image: 2205experts/restapi-k8s-image:latest
      ports:
        - containerPort: 5000