apiVersion: v1
kind: Service
metadata:
  name: restapi
  labels:
    name: restapi-service
    app: users-manager-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    name: restapi-app-pod
    app: users-manager-app