apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deploy
  labels:
    name: restapi-deploy
    app: users-manager-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      name: restapi-app-pod
      app: users-manager-app
  template:
    metadata:
      name: restapi-app-pod
      labels:
        name: restapi-app-pod
        app: users-manager-app
    spec:
      containers:
        - name: restapi-app
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP