apiVersion: v1
kind: Service
metadata:
  name: restapi
  labels:
    name: restapi-service
    app: users-manager-app
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: restapi-app-pod
    app: users-manager-app